# Generated by Django 5.1.1 on 2024-12-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_title_job_host_job_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Company',
        ),
    ]
