# Generated by Django 5.1.1 on 2024-12-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_title_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='company',
        ),
    ]
