# Generated by Django 5.1.1 on 2024-12-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_title_job_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='title',
        ),
    ]
